### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by punjab** [JillLion/two_player_game.rb#1]
- Your github username that is committing is called vagrant. Really?
- Divide into multiple methods rather than having one long method.

**Comment by JillLion** [comment]
Hi Arvinder,

Thank you for the feedback. I will go back and refactor in to multiple methods, now that I have a better understanding of that.

With regards to the github username, I'm not sure where you're seeing it listed as Vagrant. My username is JillLion. Maybe I did something wrong in my push to github. Have you ever seen that mistake before? If you could send me a link of where you're seeing it, I will look in to it.

Thank you again,
Jill
